name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Install Vercel CLI
      run: npm i -g vercel

    # Preview deploy (every push) – gets a unique URL
    - name: Vercel deploy (preview)
      if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
      run: vercel deploy ./playwright-report --token ${{ secrets.VERCEL_TOKEN }} --yes
      env:
        VERCEL_PROJECT_NAME: playwright-report

    # Production deploy (when pushing to main/master)
    - name: Vercel deploy (production)
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
      run: vercel deploy ./playwright-report --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
      env:
        VERCEL_PROJECT_NAME: playwright-report